# Generated by Django 3.0.6 on 2021-03-31 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210329_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='map.Point'),
        ),
        migrations.AddField(
            model_name='road',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
