# Generated by Django 3.0.6 on 2021-04-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20210331_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='vec_x',
        ),
        migrations.RemoveField(
            model_name='road',
            name='vec_y',
        ),
    ]
