# Generated by Django 3.0.6 on 2021-04-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20210405_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='rate',
        ),
    ]
