# Generated by Django 3.0.6 on 2021-04-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_remove_road_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='rate',
            field=models.FloatField(default=1),
        ),
    ]
