# Generated by Django 3.0.6 on 2021-05-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0026_campus_point_road'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='point',
            name='edges',
        ),
        migrations.RemoveField(
            model_name='road',
            name='campus',
        ),
        migrations.AddField(
            model_name='road',
            name='belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_roads', to='map.Point'),
        ),
        migrations.AddField(
            model_name='road',
            name='points',
            field=models.ManyToManyField(related_name='edge', to='map.Point'),
        ),
        migrations.AlterField(
            model_name='point',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_points', to='map.Point'),
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='point',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
    ]
