# Generated by Django 3.0.6 on 2021-05-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_auto_20210515_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='belong',
        ),
        migrations.RemoveField(
            model_name='road',
            name='points',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Road',
        ),
    ]
