# Generated by Django 3.0.6 on 2021-05-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0034_point_road'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='belong',
        ),
        migrations.RemoveField(
            model_name='road',
            name='points',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Road',
        ),
    ]
